### ISSUE TITLE
prevent browser.geolocation error

### ISSUE THREAD

**Issue by jacih** [MpAlfano/Off-The-Couch#3]
If block is selected once for the site, you are never asked for permission again. clearing cache does not work.

**Comment by jacih** [comment]
Add an edge case in fetchLocation name to alert users who do not share location that they will not be able to use the app

**Comment by bdubz93** [comment]
Added a function that if the user clicks block,  "For Off The Couch to work, please allow location." will be displayed on the page. Styling/actual text can be adjusted
